version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts # Using the Long-Term Support version of Jenkins
    user: root # Running as root to access Docker socket, consider security implications
    ports:
      - "8080:8080" # Exposing Jenkins on port 8080
    volumes:
      - jenkins_data:/var/jenkins_home # Jenkins data volume
      - /var/run/docker.sock:/var/run/docker.sock # Mounting the Docker socket
      - /usr/bin/docker:/usr/bin/docker # Optional: Mounting Docker binary if needed
    restart: unless-stopped
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - net

networks:
  net:

volumes:
  jenkins_data:
